# Generated by Django 5.2.1 on 2025-05-19 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxsulot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maxsulotlike',
            name='product_like_unique',
        ),
        migrations.RenameField(
            model_name='maxsulotlike',
            old_name='user',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='maxsulotlike',
            constraint=models.UniqueConstraint(fields=('author', 'product'), name='product_like_unique'),
        ),
    ]
