# Generated by Django 5.2.1 on 2025-05-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxsulot', '0003_remove_maxsulotlike_product_like_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
